version: '3.1'
services :
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passworD
      MYSQL_DATABASE: leaguey
    ports:
      - 3306:3306
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data:

    